### PR TITLE
Add preferences to menu

### PR DESCRIPTION
**Pull request by simenbw**
Added preferences to the File menu

### CODE REVIEW

**Comment by eidheim** [comment]
Thank you, but its already here: https://github.com/cppit/jucipp/blob/master/src/menu.cc#L44
You'll find it somewhere I think, either on top menu (called app menu if I remember correctly), or under juCi++ in the "normal menu"/window menu.

**Comment by zalox** [comment]
Great! @eidheim, we should add this before 1.0.1.

**Comment by zalox** [comment]
I should stop reviewing on my phone.

**Comment by eidheim** [comment]
Did you find the preference menu item? If not, what platform do you use?

**Comment by simenbw** [comment]
Found it, was on the top "App menu"

**Pull request closed without merging**
