### PR TITLE
Correct next/previous tab keys for Linux

### PR DESCRIPTION
**Pull request by eidheim**
If this works better for your Arch Linux we can merge this before v1.0.0 release.

Tested on:
- [x] Debian testing
- [x] Debian stable
- [ ] Linux Mint
- [ ] Ubuntu 14
- [x] Ubuntu 15
- [x] Arch Linux

### CODE REVIEW

**Comment by zalox** [comment]
I don't like these hot-keys. From other editors I'm used to ctrl+tab to change tabs and ctrl+shift+tab to go backwards. This is also how it's done in firefox, chrome etc.

**Comment by eidheim** [comment]
It is the default for all linux applications I have seen so far

**Comment by eidheim** [comment]
Aha, one sec, I see you can also use ctrl-tab and shift-control-tab

**Comment by eidheim** [comment]
ok I|ll change it

**Comment by eidheim** [comment]
There, its fixed:)

**Comment by zalox** [comment]
http://0o2471.net/63636

We need an option to disable the grid as well :P

**Comment by eidheim** [comment]
Lets not try to fix too much, and thus introduce new bugs now that we have a working version. The grid is part of style options, and juci looks awful anyway with the standard ugly sourceview styles.

**Comment by eidheim** [comment]
And btw, the dark style you have is the issue, not juci. The standard sourveview styles have grid settings. This is missing on the dark style. Puh, one issue gone:)

**Comment by zalox** [comment]
I haven't got any VM for ubunu 14 and debian stable right now, do you?

**Comment by eidheim** [comment]
Yeah, in about 30 minutes when Im back home.

**Comment by eidheim** [comment]
Its not actually working on Ubuntu 14, but its fixed in Ubuntu 15. I will not make a fix for Ubuntu 14 before after v1.0.0 release, if ever, as it requires some work to do this for Ubuntu 14 and not Ubuntu 15. At least now, the key binding is working for some linux distributions, as opposed as before this commit when it did not work for any. Huge improvement! Merge and release v1.0.0?

**Comment by eidheim** [comment]
@zalox ready for merge even though two items are missing, see comment above.

**Pull request merged**
