### PR TITLE
Add right margin line in sourceview

### PR DESCRIPTION
**Pull request by VJSchneid**
Add right margin line in sourceview. The margin can be activated and configured in the source section of the config file.

### CODE REVIEW

**Comment by eidheim** [comment]
Thank you, looks good! Merging soon.

**Comment by eidheim** [comment]
One thing though: would you mind changing the version from `1.3.1` to `1.3.0.1`? I'll create a `1.3.1` release later with release notes.

**Comment by VJSchneid** [comment]
Everything's fine! I have changed the version.

**Comment by eidheim** [comment]
Thank you again:)

**Pull request merged**
