### PR TITLE
Add handy shortcut: use 'Ctrl - Right Click' to go to implementation directly.

### PR DESCRIPTION
**Pull request by artisdom**
Use  'Ctrl - Right Click' to go to implementation is a very handy feature offered by other IDEs, Jucipp should have it also. :)

### CODE REVIEW

**Comment by artisdom** [comment]
Sorry, I mean 'Ctrl - Left Click', being working all day, a bit loose in the brain now.

**Comment by eidheim** [comment]
Thank you again! 

This PR require a bit more work it seems. I'll fix it later, hopefully next week or so. The improvements will be as follows:
* Command key should activate this instead of control on MacOS
* Cursor has to be placed I think before activating the menu item
* If clicking on declaration, go to implementation.
* If clicking on implementation, go to declaration.
* If clicking on usage, go to implementation.

**Comment by artisdom** [comment]
Thank you for reviewing my pull request. :)


> Cursor has to be placed I think before activating the menu item

just noticed, the cursor location need to be updated before other actions, otherwise it'll go to the wrong symble.

> If clicking on declaration, go to implementation.
> If clicking on implementation, go to declaration.
> If clicking on usage, go to implementation.

this has more usablity than what i'm proposing.

and it may also touch upon this feature.
[Feature Request: Go to File/Header](https://github.com/cppit/jucipp/issues/310)
Allow user to be able to click and go to header files directly.

**Comment by eidheim** [comment]
I updated the list to include the header files. Will try to fix that issue at the same time.

**Comment by agauniyal** [comment]
This is very good, also highlight with different color or underline to make it look like clicking a link..

**Comment by eidheim** [comment]
The above commit should fix this PR I think. Merging in a day or two.

**Comment by artisdom** [comment]
Just being trying out the new features, I never know how much I love clicking around before, thanks.

**Pull request merged**
