### PR TITLE
Git integration through libgit2

### PR DESCRIPTION
**Pull request by eidheim**
* Showing diffs as you type in source view, and changed files are marked in directory view. Updates happen automatically by monitoring `.git/index` (not entirely sure this file is the most optimal file to monitor though). 
* Added Go to Next Diff and Show Diff in Source->Git menu
* Should be stable
* Probably have to improve the colors a bit. Dark yellow is quite ugly for instance. 
* Added monitor to directories as well instead of doing manual polling. 

Also added: implement method.

### CODE REVIEW

**Comment by eidheim** [comment]
@zalox CI's are failing due to missing libgit2 dependency

**Comment by eidheim** [comment]
We should probably test this for a week or two before merge.

**Comment by zalox** [comment]
See https://github.com/cppit/jucipp-docker/commit/f840ea7977c2265b50104f15395f882a27b25bb6 travis should sort itself out in a couple of hours.

**Comment by zalox** [comment]
@eidheim Please add mingw-w64-x86_64-libgit2 to https://github.com/cppit/jucipp/blob/master/ci/update_ci.sh#L35. No need to squash it into the previous commit :)

**Comment by eidheim** [comment]
There is a crash on MSYS2 that I'll fix in a day or two

**Comment by milleniumbug** [comment]
Workaround for [window splitting](https://github.com/cppit/jucipp/commit/0406b7c1c30b9fa66feaebe03c5138255e789477) stopped working on this branch for me for some reason.

**Comment by eidheim** [comment]
@milleniumbug could you try increase the delay? It's currently `50`. Maybe 200-300 should do it?

**Comment by milleniumbug** [comment]
@eidheim Ok, that fixed it. For me, 120 was enough.

**Comment by eidheim** [comment]
@milleniumbug splendid, I'll set it to 200 then just to be sure. It's just a workaround till gtk3.22 arrives anyway:)

**Comment by eidheim** [comment]
@zalox this PR is actually ready for merge now I think. After you have reviewed and tested it of course. Implement method does not support templates yet it seems, but I'll fix that later, nothing breaking that is.

**Comment by eidheim** [comment]
I'll merge this soon. Quite well tested and should be pretty safe to merge. If there are any issues, I'll fix them in the master branch.

**Comment by zalox** [comment]
* If I delete the .git folder, the folder tree still indicates being in version control.
Besides from that, I haven't found anything.

**Comment by eidheim** [comment]
We can live with special cases such as that I guess for now.

**Comment by eidheim** [comment]
@zalox By the way, since GitHub decided to do a squash on the merge, how do I get my branch even with cppit/jucipp? Might have asked you about this before, but have forgotten the git command:)

**Comment by eidheim** [comment]
Or I guess it's safe to perform a rebase on my branch and drop my commits from when this PR was started.

**Comment by eidheim** [comment]
@zalox Never mind, I did it:)

**Comment by zalox** [comment]
```bash
# my workflow
git clone git@github.com:zalox/jucipp --recursive
# add cppit as remote
# I use https so I need to type username and password to commit to cppit/master
git remote add cppit https://github.com/cppit/jucipp.git
# 2 step merge
git pull cppit master # i substitute cppit with eidheim if I'm merging your changes
git push cppit master
```
To merge as before, but without github cleanups. I think we should disable merging from the web interface...

**Comment by eidheim** [comment]
Yeah, I did not know github did squash on the web merge button, should have read more carefully. Normally I pull and merge using command line.

**Pull request merged**
