### PR TITLE
Terminal and fonts

### LINKED ISSUE #179: The Terminal should use monospace font
The terminal below the editor, that logs all actions and is Used to take input If I run a program with `cin`, can be improved by having mono space font.

Also, When the code runs, It can clear the screen so it is more intuitive that the code is running fine and input can be made.

Also, Also, Tab height can be increased.

PS. Your project is one of the first programs that safely and successfully compiled and installed from source.

### PR DESCRIPTION
**Pull request by zalox**
Fixes #179. Ready for merge after being tested on the various platforms. Consider this v1.1.2 release candidate.

### CODE REVIEW

**Comment by eidheim** [comment]
This is somewhat messy, I would prefer the way it was. The issue gets more links, and yeah, messy;)

**Comment by eidheim** [comment]
Also, part of the version change was due to changes in files.h. Without a version change, a user's config.json will not update.

**Comment by eidheim** [comment]
But I see that its not possible to reopen my PR with the same id, so just merge this one this time. Just do not do this in the future please:)

**Comment by zalox** [comment]
This is a fairly common way of cleaning up commit trees, I've seen it done a lot in atom for instance. I reverted the PR, so you can continue working on your branch :)

I'm going to be a bit more strict with commits in the future. Now when the project is becoming quite popular, it is important that the commits are readable and concise. I got more spare time to manage this now in April and forwards.

It is important to note that I will not refactor the commits again, unless asked, I just feel like we need to spend some more time on creating the pull requests in the first place, so that developers can understand what's going on when reading them :)

**Comment by eidheim** [comment]
I'll clean up the commits once I learn the git magic back and through.

**Pull request closed without merging**
