### PR TITLE
Use italic font for comment, more ease on the eyes.

### PR DESCRIPTION
**Pull request by artisdom**
as titled, cheers.

### CODE REVIEW

**Comment by eidheim** [comment]
Thank you for your PRs! I'll have a look at them soon.

**Comment by eidheim** [comment]
Maybe I'm used to how it is, but I also see that GitHub for instance uses normal fonts for comments. Keep it as it is, or? I think more people should comment on this, before we close or merge this PR.

**Comment by artisdom** [comment]
While it is customizable through config file, so enjoy it already, cheers.

**Comment by zalox** [comment]
If the user would like italics on comments I suppose he could just edit the theme file in `.juci/styles`.

**Pull request closed without merging**
