### PR TITLE
Clicking on compiler error in terminal

### PR DESCRIPTION
**Pull request by hia3**
navigates to the file with error

### CODE REVIEW

**Comment by eidheim** [comment]
Thank you again, I'll merge this Tomorrow morning most likely. Although I'll probably make some slight changes.

**Comment by hia3** [comment]
How about using the same format (file:line:offset) in last_session.json/files? So may be you'll do something to reuse while doing your changes. :)

**Comment by eidheim** [comment]
I would rather not create a 100% full path:line:index parser, especially if someone decided to put ':' and spaces in their file names. The current one works in 99% of the cases, and I'm happy with that.

**Comment by eidheim** [comment]
Also, I'll add View::place_cursor_safe and other methods later to reduce the duplicate code found in refactoring methods and in Terminal::on_button_press_event.

**Comment by milleniumbug** [comment]
Doesn't work when Ninja is used as a generator. Probably the same reason as [this](https://github.com/cppit/jucipp/issues/177).

**Comment by eidheim** [comment]
I'll fix it Tomorrow morning. Thanks!

**Comment by hia3** [comment]
I'd like to mention 2 minor things: 
1) errors from cmake (make?) could be made clickable (this is why I had to write that nested try block), marked on the picture;

not_highlighted

2) in last_session.json paths look weird:

    "files": [
        "D:\\dev\\jucipp\\src\\source.cc",
        "D:\/dev\\jucipp\\src\\terminal.cc"
    ],

Here source.cc was opened from the tree, but terminal.cc was opened from terminal link.

**Comment by eidheim** [comment]
@hia3 Would anyone want to open the autogenerated build files that are marked in red? If so, I could mark them as well as links (and the fix to the issue @milleniumbug posted will fix opening these files too). 

Regarding 2, I'll have a look at the MSYS2 paths as well Tomorrow. My initial tests showed that it worked, but paths on MSYS2 are still sometimes problematic. Just to be sure, have you upgraded MSYS2 lately?

**Comment by eidheim** [comment]
@hia3 I think the weird looking paths on Windows is only a visual issue, and does not affect juCi++ at all otherwise. Please feel free to correct me if I'm wrong.

**Comment by eidheim** [comment]
See above commit. I decided not to add links to autogenerated build files, I think most people do not want to touch these!:)

**Pull request merged**
