### PR TITLE
Major cleanup of clang parsing and autocomplete

### PR DESCRIPTION
**Pull request by eidheim**
We should wait a few days before merging the latest commit (https://github.com/eidheim/jucipp/commit/7b78a6aea9ee5a8ecbf2935b397be50bcae34737) as it needs more testing. 
Same goes for this commit: https://github.com/eidheim/jucipp/commit/fd4668bfe4f313aeee46cc593daaf1d823a76c67

### CODE REVIEW

**Comment by eidheim** [comment]
Thank you for the checkboxes! See latest commit for correct link. You can now test this PR with `git clone --recursive http://github.com/eidheim/jucipp`.

**Comment by VadimGit** [comment]
no problem on arch x64 stable

**Comment by eidheim** [comment]
See updated PR message on top.

**Comment by eidheim** [comment]
Have cleaned up the core of juCi++; the clang processing and autocomplete. I hope it's more readable, but it is quite complex either way. We need to test this PR thoroughly before merging it. Please respond here if you find any bugs.

**Comment by zalox** [comment]
I got some time later tonight, I'll test in windows and arch.

**Comment by eidheim** [comment]
It seems pretty stable, I have experienced no issues at least while writing the latest 7 commits.

**Comment by eidheim** [comment]
Latest changes tested on Ubuntu 14, Debian testing and OS X.

**Comment by zalox** [comment]
No crashes here either.

**Comment by eidheim** [comment]
I think its ready for merge then:)

**Comment by zalox** [comment]
I crashed now, I don't know what happened exactly but I was closing a tab.

```bash
** Info: /home/zalox/projects/juci/src/juci.cc@init_logging(11): "Logging initalized"
** Debug: /home/zalox/projects/juci/src/window.cc@Window(25): "start"
** Debug: /home/zalox/projects/juci/src/directories.cc@update(144): "start"
** Debug: /home/zalox/projects/juci/src/directories.cc@update(150): "end"
** Debug: /home/zalox/projects/juci/src/window.cc@Window(126): "end"
** Debug: /home/zalox/eidheim/src/notebook.cc@open(59): "start"
** Debug: /home/zalox/eidheim/src/notebook.cc@open(59): "start"
** Debug: /home/zalox/eidheim/src/notebook.cc@open(59): "start"
** Debug: /home/zalox/eidheim/src/notebook.cc@open(59): "start"
** Debug: /home/zalox/eidheim/src/notebook.cc@open(59): "start"
** Debug: /home/zalox/eidheim/src/notebook.cc@open(59): "start"
** Debug: /home/zalox/eidheim/src/directories.cc@select(154): "start"
** Debug: /home/zalox/eidheim/src/directories.cc@select(194): "end"
** Debug: /home/zalox/eidheim/src/notebook.cc@open(59): "start"
** Debug: /home/zalox/eidheim/src/source_clang.cc@ClangViewParse(25): "start"
** Debug: /home/zalox/eidheim/src/source_clang.cc@ClangViewParse(74): "end"
** Debug: /home/zalox/eidheim/src/directories.cc@select(154): "start"
** Debug: /home/zalox/eidheim/src/notebook.cc@open(150): "end"
** Debug: /home/zalox/eidheim/src/notebook.cc@close_current_page(255): "start"
** Debug: /home/zalox/eidheim/src/directories.cc@select(154): "start"
** Debug: /home/zalox/eidheim/src/directories.cc@select(194): "end"
** Debug: /home/zalox/eidheim/src/notebook.cc@close_current_page(283): "end true"
```

**Comment by eidheim** [comment]
Did you close the tab using the new close symbol or keys?

**Comment by eidheim** [comment]
Also, did you move around the tabs before closing?

**Comment by zalox** [comment]
No, I haven't pulled latest updates.

I might have clicked the tab, ctrl + w and opened the next one. It was briefly after jumping to declaration in a gtk-header. The parsing was complete.

**Comment by eidheim** [comment]
See if you can manage to reproduce the steps that create the crash, like 90% of the cases it happens when performing the same steps again.

**Comment by zalox** [comment]
I get this in stderr when opening foreign files:
```bash
LIBCLANG TOOLING ERROR: json-compilation-database: Error while opening JSON database: No such file or directory

```

**Comment by eidheim** [comment]
That is from libclang and is because there is no compile_commands.json for the file. We could maybe suppress this message, but the message is not important. We could, however, maybe consider activating c++11 for instance for files missing compile_commands.json.

**Comment by zalox** [comment]
I think it's possible to determine c/cxx-type on a file by using the cmake binary.

**Comment by eidheim** [comment]
I manage to reproduce the crash, gdb backtrace:
```sh
#0  0x0000000101652373 in get_buffer () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#1  0x0000000100e4cd27 in Gtk::TextView::get_buffer() () from /usr/local/opt/gtkmm3/lib/libgtkmm-3.0.1.dylib
#2  0x0000000100031252 in sigc::internal::slot_call2<Source::View::set_tooltip_events()::$_4, void, Gtk::TextIter const&, Glib::RefPtr<Gtk::TextMark> const&>::call_it(sigc::internal::slot_rep*, Gtk::TextIter const&, Glib::RefPtr<Gtk::TextMark> const&) ()
#3  0x0000000100e4602a in (anonymous namespace)::TextBuffer_signal_mark_set_callback(_GtkTextBuffer*, _GtkTextIter const*, _GtkTextMark*, void*) () from /usr/local/opt/gtkmm3/lib/libgtkmm-3.0.1.dylib
#4  0x0000000101dd941a in g_closure_invoke () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#5  0x0000000101dee66d in signal_emit_unlocked_R () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#6  0x0000000101def042 in g_signal_emit_valist () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#7  0x0000000101def712 in g_signal_emit () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#8  0x0000000101639333 in gtk_text_buffer_mark_set () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#9  0x00000001016390a4 in gtk_text_buffer_set_mark () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#10 0x0000000101fe5571 in gtk_text_region_add () from /usr/local/opt/gtksourceview3/lib/libgtksourceview-3.0.1.dylib
#11 0x0000000101fd804c in update_syntax () from /usr/local/opt/gtksourceview3/lib/libgtksourceview-3.0.1.dylib
#12 0x0000000101fdadbe in idle_worker () from /usr/local/opt/gtksourceview3/lib/libgtksourceview-3.0.1.dylib
#13 0x0000000101a60ce3 in gdk_threads_dispatch () from /usr/local/opt/gtk+3/lib/libgdk-3.0.dylib
#14 0x0000000101e4513b in g_main_context_dispatch () from /usr/local/opt/glib/lib/libglib-2.0.0.dylib
#15 0x0000000101e45425 in g_main_context_iterate () from /usr/local/opt/glib/lib/libglib-2.0.0.dylib
#16 0x0000000101e4547d in g_main_context_iteration () from /usr/local/opt/glib/lib/libglib-2.0.0.dylib
#17 0x000000010008d294 in std::__1::__function::__func<Window::set_menu_actions()::$_32, std::__1::allocator<Window::set_menu_actions()::$_32>, void ()>::operator()() ()
#18 0x000000010128a0e0 in (anonymous namespace)::SimpleAction_signal_activate_callback(_GSimpleAction*, _GVariant*, void*) ()
   from /usr/local/opt/glibmm/lib/libgiomm-2.4.1.dylib
#19 0x0000000101dd941a in g_closure_invoke () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#20 0x0000000101dee66d in signal_emit_unlocked_R () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#21 0x0000000101def042 in g_signal_emit_valist () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#22 0x0000000101def712 in g_signal_emit () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#23 0x0000000101bc997e in g_simple_action_activate () from /usr/local/opt/glib/lib/libgio-2.0.0.dylib
#24 0x0000000101237faf in Gio::Action_Class::activate_vfunc_callback(_GAction*, _GVariant*) ()
   from /usr/local/opt/glibmm/lib/libgiomm-2.4.1.dylib
#25 0x00000001014cdbf9 in gtk_action_muxer_activate_action () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#26 0x00000001014cdbf9 in gtk_action_muxer_activate_action () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#27 0x00000001014df174 in gtk_application_activate_accel () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#28 0x00000001016ac8b3 in gtk_window_activate_key () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#29 0x00000001016af407 in gtk_window_key_press_event () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#30 0x0000000100e739e5 in Gtk::Widget::on_key_press_event(_GdkEventKey*) () from /usr/local/opt/gtkmm3/lib/libgtkmm-3.0.1.dylib
#31 0x0000000100e6de91 in Gtk::Widget_Class::key_press_event_callback(_GtkWidget*, _GdkEventKey*) ()
   from /usr/local/opt/gtkmm3/lib/libgtkmm-3.0.1.dylib
#32 0x00000001015aecb1 in _gtk_marshal_BOOLEAN__BOXEDv () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#33 0x0000000101dd9647 in _g_closure_invoke_va () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#34 0x0000000101deed9f in g_signal_emit_valist () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#35 0x0000000101def712 in g_signal_emit () from /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
#36 0x000000010169c978 in gtk_widget_event_internal () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#37 0x00000001015adcff in propagate_event () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#38 0x00000001015ad62f in gtk_main_do_event () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
#39 0x0000000101a7e868 in gdk_event_dispatch () from /usr/local/opt/gtk+3/lib/libgdk-3.0.dylib
#40 0x0000000101e4513b in g_main_context_dispatch () from /usr/local/opt/glib/lib/libglib-2.0.0.dylib
#41 0x0000000101e45425 in g_main_context_iterate () from /usr/local/opt/glib/lib/libglib-2.0.0.dylib
#42 0x0000000101e4547d in g_main_context_iteration () from /usr/local/opt/glib/lib/libglib-2.0.0.dylib
#43 0x0000000101bc10d2 in g_application_run () from /usr/local/opt/glib/lib/libgio-2.0.0.dylib
#44 0x000000010000b281 in main ()
```

**Comment by zalox** [comment]
Seems like the buffer gets referenced after the tab is closed.

**Comment by eidheim** [comment]
Yeah, it is probably the sigc::connection's that are not disconnected before destructions. Fixing it now.

**Comment by eidheim** [comment]
Ah I understand the problem now for the first time. The reason is that destruction of the object when closing a tab is delayed because of the libclang processing, so we have to close all of the _connection objects (of timeouts and Glib::dispatchers) in Source::ClangView::async_delete. Committing fix in a sec.

**Comment by eidheim** [comment]
To clear up abit my last post, the tab is closed, but the source object is not immediately destroyed, and then the delayed functions and dispatchers might run without having a buffer to process on, which leads to the crash.

**Comment by eidheim** [comment]
It's still crashing, I'll have a look at it Tomorrow instead.

**Comment by zalox** [comment]
I'm experiencing some weird behaviour:
```bash
Tab char and size for file /home/zalox/.juci/config/config.json set to: <space>, 4.
Language for file /home/zalox/.juci/config/config.json set to JSON.
Tab char and size for file /home/zalox/projects/juci/src/menu.cc set to: <space>, 11.
Parsing /home/zalox/projects/juci/src/menu.cc..........done
Parsing /home/zalox/projects/juci/src/notebook.cc.......canceled, freeing resources in the background
Tab char and size for file /home/zalox/projects/juci/src/menu.h set to: <space>, 6.
Parsing /home/zalox/projects/juci/src/menu.h.......done
```
Tab size seems to live its own life... (I tried to delete ~/.juci/config/config.json)

**Comment by eidheim** [comment]
Yeah, the logic in getting tab size needs to be improved.

**Comment by eidheim** [comment]
The crash discussed above is fixed.

**Comment by eidheim** [comment]
This PR is ready for merge, saying that with some more confidence now:) It also fixes a few crashes and bugs. I'll have a look at the auto indent setting function later, and will create a new pull request, hopefully, that improves that function.

**Comment by eidheim** [comment]
Merging this PR now, since it is more stable than the master branch, and have been tested quite well.

**Pull request merged**
