### PR TITLE
Terminal and fonts

### LINKED ISSUE #179: The Terminal should use monospace font
The terminal below the editor, that logs all actions and is Used to take input If I run a program with `cin`, can be improved by having mono space font.

Also, When the code runs, It can clear the screen so it is more intuitive that the code is running fine and input can be made.

Also, Also, Tab height can be increased.

PS. Your project is one of the first programs that safely and successfully compiled and installed from source.

### PR DESCRIPTION
**Pull request by eidheim**
Fixes #179. Ready for merge after being tested on the various platforms. Consider this v1.1.2 release candidate.

### CODE REVIEW

**Comment by eidheim** [comment]
@zalox tested and works on most platforms. Ready for merge. Will do only bug fixes now before I'll release v1.1.2, in a week or so.

**Comment by zalox** [comment]
Please make this into one commit.
```
git reset --soft 670d4bb
git add -p
git commit --amend
git push origin suggestion-terminal-and-fonts --force
```
When jumping through `add -p`, please omit the version bump and make that into a standalone commit.

Or you can push it to an branch on cppit and I'll fix it my self :)

**Comment by eidheim** [comment]
I don't have time to learn this now, but I will in the future!

**Comment by zalox** [comment]
@eidheim I managed to hack it :)

**Comment by eidheim** [comment]
I'm merging this now, we need people to test this release candidate.

**Pull request merged**
