### PR TITLE
Better auto indent tab char and size setting and link to improved tiny-process-library

### PR DESCRIPTION
**Pull request by eidheim**
Tested on OS X, MSYS2, Debian stable/testing and Ubuntu 14. Ready for merge.

### CODE REVIEW

**Comment by eidheim** [comment]
@zalox After we have agreed upon the screenshot issues, I think this branch is a good release candidate for v1.0.0! 

@oyvang Would be nice if you could test this as well:)

**Comment by eidheim** [comment]
Ok this PR is ready for merge. Tested on OS X, Debian stable/testing, MSYS2 and Ubuntu 14. 

@zalox Proposing that we release master as v1.0.0 after merge!:)

**Comment by eidheim** [comment]
I just now saw this: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-jucipp-git !

Our first distributed package, congrats all:)

We should create a pull request on this package when we have the v1.0.0 release ready.

**Comment by eidheim** [comment]
Minor fix to autocompletion error coming soon, only affects OS X in rare conditions as far as I know.

**Comment by zalox** [comment]
Ohh nice! @oyvang @tedjk You should get in on this. I love it!

I'm reviewing the merge now.

**Pull request merged**
