### PR TITLE
New python plugin implementation

### PR DESCRIPTION
**Pull request by zalox**
# Features
* Write plugins in python using an API-module
* Configure integration with juCi++ usin JSON configuration
* Easy expansion of the API using lamba expressions in `python_api.cc`

# libjuci - Python API for juCi++
### libjuci.
```c++
  add_menu_element(str json) // -> (void) Builds a menu configured by 'json'
```
```json
[
    {
        "label": "_Edit",
        "menu_elements": [
            {
                "label":"_Snippet",
                "menu_elements": [
                    {
                        "label":"Insert snippet",
                        "keybinding":"<primary>m",
                        "action":"snippet.insert_snippet"
                    }
                ]
            }
        ]
    }
]

```
```c++
  get_juci_home() // -> (str) returns the path of the juci home folder
```
### libjuci.terminal
```c++
  println(str message) // -> (int) prints 'message' to terminal
```
### libjuci.editor
```c++
    erase(int, int); // -> (void) removes the text between the given offsets
    erase_line_range(int, int, int); // -> (void) Removes text on line 'line_number' between 'begin_line_offset' and 'end_line_offset'
    get_file(); // -> (str) Returns the current open file. If no file is open it returns empty a string
    get_highlighted_word(); // -> (str) returns json, empty string on error{'word': 'word','type': '-1'}
    get_line(); // -> (str) returns the line of text the caret is on
    get_line_number(); // -> (int) Returns the line which is being edited, -1 if no file is open or no line is selected
    get_line_offset(); // -> (int) Returns the number of characters the caret currently is positioned from the previous newline, 0 is the first character -1 if no file is open or no line is selected
    get_offset(); // -> (int) Returns the number of characters the caret currently is positioned from start of the file. 0 is the first character. Returns -1 if no lines or files are selected/open
    get_tab_char_and_size(); // -> (str) Returns a key-value json-object with 'tab_char' and 'size' keys
    get_text(); // -> (str) returns the text in the open editor
    get_text_range(int, int); // -> (str) Returns the text between 'begin_offset' and 'end_offset'. Returns emptystring if editor isn't focused on a file
    insert_at(int offset, str text); // -> (void) Inserts text at the given offset, caller is responsible to scroll to the insertion
    insert_at_cursor(str); // -> (void) Inserts text at the cursor
    is_saved(); // -> (bool) Returns true if the current open file is saved
    scroll_to(int line_number); // -> (void) Scrolls cursor to 'char_offset'
```

# Example plugins
## Toolsplugin 
 * Open favorite project folder using hotkey
 * Open plugin folder for easy access

## Snippet
 * Insert string templates based on keywords
```html
if -hotkey-> if () {
}
```
# Todo
- [ ] Write documentation for the API
- [ ] Test on osx @eidheim 
- [ ] Test on arch
- [ ] Test on debian
- [ ] Test on msys

- [ ] Ready for merge

### CODE REVIEW

**Comment by eidheim** [comment]
Great work! Have not looked at it thoroughly yet, but its really nice that we get a python integration that support c++11!

**Comment by zalox** [comment]
This solution doesn't work in windows very well I will need to do some refactoring.

**Comment by zalox** [comment]
Since the interpreter can tell us about code semantics I'm parsing the files with py-extension to detect syntax errors. (and mark them) I might need some help with some race conditions.

**Comment by eidheim** [comment]
@zalox Sure, let me know. I am abit busy in the following days though, have to grade some hundreds of exams. Also, would be nice if you could test https://aur.archlinux.org/packages/jucipp-git/ Tomorrow after merge of #137 and v1.0.1 release.

**Comment by eidheim** [comment]
@zalox Also, after merge Tomorrow, there are new build instructions to reflect the new build system. Easier to work with juCi++ when following these, as then you would never be affected by cmake caches in the jucipp source directory.

**Comment by archshift** [comment]
@eidheim the AUR package still works, I just tested it. It was always using out-of-source builds as described in the new build instructions.

**Comment by eidheim** [comment]
@archshift Thank you, happy to hear it. By the way, would it be ok to upgrade the AUR package to using the v1.0.1 release? Someone might experience build problems in juCi++ due to cmake caches in projects when upgrading from juCi++ v1.0.0 (in-source) to v1.0.1 or higher (out-of-source).

**Comment by archshift** [comment]
The AUR package is a devel package, that is, it pulls directly from git whenever a user chooses to install it. The build directory isn't necessarily kept the same between upgrades, either, so changes in the build system shouldn't make a problem.

**Comment by eidheim** [comment]
@archshift Ah, so when someone installs the AUR package, it fetches the latest cppit/jucipp master? I thought it cloned a specific revision/commit hash. 

The build problems I was thinking of is when compiling a project within juCi++, not when building the juCi++ application. I was a bit unclear there.

**Comment by archshift** [comment]
Yeah, it just fetches the latest revision, at least with the jucipp-git package. Also, building a project within the IDE works as well.

**Comment by eidheim** [comment]
@archshift Thank you again. So if I understand it correctly, it fetches our latest (non-pre) release (atm v1.0.1) and will ignore what we do in the master branch between the releases?

**Comment by archshift** [comment]
Nope, it fetches the latest got revision from master, tagged as a release or otherwise.

**Comment by zalox** [comment]
The arch package should behave the same way as  the msys2-package. It clones master during build.

**Comment by eidheim** [comment]
I managed to confuse myself when reading https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git I think. If I am not completely off, there is an option to base it on releases as well, but it is fine the way it is of course. 

Good thing you mentioned the MSYS2 package (https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-jucipp-git/PKGBUILD), since it is then missing the tiny-process-library link. I'll try make a PR on that Tomorrow afternoon.

**Comment by zalox** [comment]
This is testable now. @eidheim 

You might need to start juci++ twice to activate the plugins on first run. (I can't both create files and change the menu, since the menu is immutable.)

**Comment by eidheim** [comment]
@zalox see #162. I added the possibility to modify the menus at runtime, for instance:
```c++
auto plugins_submenu=Gio::Menu::create();
Menu::get().window_menu->insert_submenu(5, "Plugins", plugins_submenu);
plugins_submenu->append("Test", "app.plugins.test");
```

**Comment by zalox** [comment]
> @zalox see #162. I added the possibility to modify the menus at runtime, for instance:
> ```c++
> auto plugins_submenu=Gio::Menu::create();
> Menu::get().window_menu->insert_submenu(5, "Plugins", plugins_submenu);
> plugins_submenu->append("Test", "app.plugins.test");
> ```
I will make appropriate changes to afflict this.

I also updated the first post.

**Comment by eidheim** [comment]
@zalox By the way, is it possible to take advantage of the Python bindings to gtk3? For instance receive the current view as a python object (https://developer.gnome.org/pygtk/stable/class-gtktextview.html for instance)? Not sure if this is the best idea, but maybe worth considering as this would lead to greater flexibility when creating python plugins, and one would not need to create wrappers to all the gtktextview methods (since they already exist in pygtk).

**Comment by eidheim** [comment]
@zalox Sorry, I made another conflict, a minor one though. Committed a few fixes to master directly, and made a bugfix/cleanup release v1.1.1.

**Comment by zalox** [comment]
`eidheim wrote:`
> By the way, is it possible to take advantage of the Python bindings to gtk3? For instance receive the current view as a python object?

Yes, this is the objective of the PyGObject (GI) project. First it will make us dependent on the GI-package for python, then I need to figure out how to correctly pass references or pointers to python to create GI-objects. At the moment I have no idea how to do this, but totally agree that this approach is the best.

Just to mention why I'm not focusing on pygtk:
`pygtk.org wrote:`
 > Note: New users are encouraged to use GTK+3 through the PyGObject bindings instead of using PyGTK with GTK+2. Windows users may still want to keep using PyGTK until more convenient installers are published.

`eidheim wrote:`
> Sorry, I made another conflict, a minor one though.

Don't worry about conflicts, I'm usually happy to do them since I need to understand the algorithms they break.

_Resources for later:_
* [PyGObject reference](http://lazka.github.io/pgi-docs/)

**Comment by eidheim** [comment]
@zalox is this the one that is recommended (PyGObject): https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-pygobject? If so, it seems available through MSYS2? I have no experience with this though.

**Comment by zalox** [comment]
@eidheim Just want to mention you create standalone dialogs, windows, promptboxes etc. using the GI-library for Python as is.

`@eidheim wrote:`
> @zalox is this the one that is recommended (PyGObject): https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-pygobject? If so, it seems available through MSYS2? I have no experience with this though.

Yes, that is the correct one.

**Comment by zalox** [comment]
http://www.ibm.com/developerworks/library/l-wrap/

**Comment by zalox** [comment]
https://github.com/wcremeika/thesis/blob/5b4c04771c8fd82129f0a3151bd582e379f5aa61/claws-mail-3.9.2/src/plugins/python/clawsmailmodule.c

**Comment by zalox** [comment]
@eidheim 

This is getting very stable. The last few commits are adding menu elements and accels dynamically. The gtk bindings are working according to [the api](http://lazka.github.io/pgi-docs/), and is slightly different from the gtkmm bindings.

I've successfully tested stand-alone python apps as well, so people can write for instance gtk-windows to add gui to their plugins.

The plugins provided are made on the fly, and might need some clean up from someone who actually knows python better than me.

I'm keeping the old way of adding menu elements as well, to make sure we support plugins on systems where pygobject introspection isn't supported.

This is my todo:
* Update documentation to add new dependencies
* Make sure plugins are installed on startup
* Write some usage/design spec

**Comment by zalox** [comment]
The latest commit makes this testable. 

Python handles packages through pip or the package repo. I used pacman on arch to install pygobject and python 3 and used the site_packages option in config.json to pont to it. The default value migth be sufficent.

**Comment by eidheim** [comment]
Great! Usually, maybe before documentation etc, one would want to clean up/reconstruct the source code once having a working version. Might be a good idea to spend some time on this, especially after so many changes, and when creating an API. Saying this before I have looked at the source though, but when you are happy with the source after considering cleanup/reconstruct I'll have a look at it:)

**Comment by zalox** [comment]
I think it might be useful to rebase this pull request to get a better overview of the changes. This will also allow me to fine comb all the code to check for refactor needs. I have some time tomorrow to do this. I think most of the commits in this request are overwritten anyways. I think I can make this into more like 10 commits.

**Comment by eidheim** [comment]
Splendid, just remember to take your time on the refactor, its a great experience, and something that is not at all prioritised in businesses. This is one of the reasons why Open Source is such a success I belive:)

**Comment by zalox** [comment]
Before I start. Are there any features you'd like to see?

I think I might be able to make the bindings available for js, vala, lua and other script languages with some struggle.

**Comment by eidheim** [comment]
Python is fine for now I think:) Just keep it simple, but flexible and general.

**Pull request closed without merging**
