### PR TITLE
Similar tokens now get bold property when moving insert-cursor.

### PR DESCRIPTION
**Pull request by eidheim**

### CODE REVIEW

**Comment by eidheim** [comment]
There are some issues with parsing and autocomplete sometimes both being stopped after the user pauses input, typically after autocomplete running. Will fix this soon.

**Comment by zalox** [comment]
I'm getting very strange behaviour with this feature. Sometimes it works as it should, I suppose, but other times it bolds randomly in the nearest area. See screenshot below.

screen

**Comment by eidheim** [comment]
Can you check if the latest versions of libclangmm and jucipp works now?

**Comment by zalox** [comment]
Merged this in now, it worked perfectly this time. Great work!

**Pull request merged**
