### PR TITLE
added gui buttons for finding/replacing

### PR DESCRIPTION
**Pull request by milleniumbug**
using [↑][⇄][↓] for "Find Previous", "Replace current", "Find Next"
see issue #170

### CODE REVIEW

**Comment by zalox** [comment]
Great work! Do you mind adding tooltips for the remaining buttons as well? I imagine you can find suitable descriptions ;)

**Comment by eidheim** [comment]
Thanks! Merging this now, and you can decide if you'd like to add the other tooltips later. Also, closing #170.

**Comment by eidheim** [comment]
I'll commit some improvements to the find box in #171 soon.

**Comment by milleniumbug** [comment]
I'm not sure about the improvements. Although I very like "aA" and ".*" to mean case sensitive/insensitive search and regex search, the other parts are less clear than I would like them to be.

More specifically "⇧Enter" and "Enter in Entry". The former is a minor complaint - this deviates in style from listing shortcuts in Menu bar dropdown menus which do so in more traditional way "Shift+Enter". The "Enter in Entry" is more of an issue - there are two "entries" there, and it's not clear enough which one do you mean (well, ok, maybe you do), but using a word "Entry" to mean "text box control" is... vexing. Well, both words are normally used, but "entry" has more meanings, which would make it unclear.

I prefer the previous "search field" and "replacement field" terms.

**Comment by eidheim** [comment]
I agree, will fix it Tomorrow. The correct wording is maybe "Find entry field" and "Replace entry field"?

**Comment by milleniumbug** [comment]
Wasn't sure about it, but I googled the terms, and there are some websites mentioning them, so it's probably OK.

**Comment by eidheim** [comment]
At least https://developer.gnome.org/gtk3/stable/GtkEntry.html uses it. Another possibility is "Find text entry" and "Replace text entry", but I'm leaning towards "entry field" instead of "text entry". I'm not an english native speaker though.

**Comment by milleniumbug** [comment]
Neither am I, so I googled the term "find entry field" - it yields 225 results, but at least the context is relevant. Still, I won't give up hope, maybe there is a better term.

**Comment by eidheim** [comment]
Return is used in the gtk menu instead of enter, so at the moment I propose:
```diff
diff --git a/src/window.cc b/src/window.cc
index 23540bf..7641fb2 100644
--- a/src/window.cc
+++ b/src/window.cc
@@ -896,18 +896,18 @@ void Window::search_and_replace_entry() {
     if(notebook.get_current_page()!=-1)
         notebook.get_current_view()->search_backward();
   });
-  EntryBox::get().buttons.back().set_tooltip_text("Find Previous (shortcut: ⇧Enter in entry)");
+  EntryBox::get().buttons.back().set_tooltip_text("Find Previous\n\nShortcut: Shift+Return in the Find entry field");
   EntryBox::get().buttons.emplace_back("⇄", [this, replace_entry_it](){
     if(notebook.get_current_page()!=-1) {
       notebook.get_current_view()->replace_forward(replace_entry_it->get_text());
     }
   });
-  EntryBox::get().buttons.back().set_tooltip_text("Replace Next (shortcut: Enter in entry)");
+  EntryBox::get().buttons.back().set_tooltip_text("Replace Next\n\nShortcut: Return in the Replace entry field");
   EntryBox::get().buttons.emplace_back("↓", [this](){
     if(notebook.get_current_page()!=-1)
       notebook.get_current_view()->search_forward();
   });
-  EntryBox::get().buttons.back().set_tooltip_text("Find Next (shortcut: Enter in entry)");
+  EntryBox::get().buttons.back().set_tooltip_text("Find Next\n\nShortcut: Return in the Find entry field");
   EntryBox::get().buttons.emplace_back("Replace All", [this, replace_entry_it](){
     if(notebook.get_current_page()!=-1)
       notebook.get_current_view()->replace_all(replace_entry_it->get_text());
```

**Comment by eidheim** [comment]
The entry fields are named Find and Replace, so that I why I'm using "Find entry field" and "Replace entry field".

**Comment by milleniumbug** [comment]
I've checked it and it seems it depends on the current locale - on mine it's Enter, on en_US it's Return. 

It doesn't matter to me which one of these will be, but, just so you know.

**Comment by eidheim** [comment]
Ended up with: https://github.com/cppit/jucipp/commit/6f2792969adc4af2c4692eb298751d31271180c9

**Pull request merged**
