### PR TITLE
All MSYS2 paths should now be ok

### PR DESCRIPTION
**Pull request by eidheim**

### CODE REVIEW

**Comment by zalox** [comment]
You can directly push to cppit:various_fixes, no need to make a PR

**Comment by eidheim** [comment]
Have to change my test scripts according to branch name, which is annoying, so i just work on eidheim/master:)

**Comment by eidheim** [comment]
Btw have to check if there is a better way to get the directory tree file focus correct (on all platforms). Will have a look at this Tomorrow.

**Comment by zalox** [comment]
I feel like I need to clarify, you don't need to create Pull requests on github to push to the cppit:various_fixes.

```bash
git remote add cppit https://github.com/cppit/jucipp.git
git push origin master # pushes to /eidheim/jucipp
git push cppit various_fixes # pushes to /cppit/jucipp
```

**Comment by eidheim** [comment]
Aha thank you, I still feel like a git when using git;)

And if I push to both there will be no trouble later when comparing eidheim/jucipp with cppit/jucipp?

**Comment by zalox** [comment]
```bash
git pull cppit master
# resolve conflicts and commit, if any
git push origin master # to your master
```
Now github should filter away any code also commited to cppit/master for instance.

If you:
```bash
git push cppit master
```
Would be the same as hitting the merge button in github.

**Pull request merged**
