### PR TITLE
Reopens last folder and files when starting juci without parameters. Also improved debug tooltips.

### PR DESCRIPTION
**Pull request by eidheim**

### CODE REVIEW

**Comment by eidheim** [comment]
@zalox A small PR, should be safe to merge after you look through it. Tested on most platforms. Also checked that the exception handling worked on MSYS2 in this PR. I don't get why it does not work in all cases.

**Comment by eidheim** [comment]
@zalox Found a way to improve the debug tooltips! Maybe do a little more testing before merging.

**Comment by eidheim** [comment]
That is, class member values, for instance, are now getting value tooltips.

**Comment by eidheim** [comment]
@zalox This PR seems ready for merge anyway. Tested on most platforms.

**Comment by zalox** [comment]
Sorry for being late on this. I will review and merge tonight.

**Comment by zalox** [comment]
Please merge when ready!

**Pull request merged**
