### PR TITLE
Various improvements and features

### PR DESCRIPTION
**Pull request by eidheim**
Latest version of libclangmm (currently in pull request) needed. 

Tested on OS X, Debian stable/testing, Ubuntu 14 and MSYS2.

This is fixed: Warning on MSYS2: when you upgrade to newest package versions, there are currently bugs in libclang 3.7 and gtk somewhere. But opening and working on a new simple C++ project should work. We just have to wait till libclang and MSYS2 fixes their bugs. 

Edit: fixed MSYS2 issues.

### CODE REVIEW

**Comment by zalox** [comment]
I used the libclang.dll file from llvm.org. Using the windows installer for libclang, it worked great with juci code. Had some problems with some incomplete types in windows.h though.

**Comment by eidheim** [comment]
Ah nice, hopefully it works with this pull as well. I did remove some quickfixes for the old msys2 libclang package.

**Comment by eidheim** [comment]
I think I got all the smaller issues fixed now, at least those I know about. Should be quite safe to merge this pull request, it seems stable on all platforms.

**Comment by eidheim** [comment]
Also remember the libclangmm pull request:)

**Pull request merged**
