### PR TITLE
Some fixes, but most notably the directory window is now a properish file manager

### PR DESCRIPTION
**Pull request by eidheim**

### CODE REVIEW

**Comment by eidheim** [comment]
Btw, we are getting close to a Github-release (1.0 or something). My TODO list is quite short now, and only contains smaller things like finding indentation char and size automatically from files and deactivation/activation of menu items, and such. I guess we can do that after we get the Windows version running through Cygwin. We can wait with python-plugins I guess. 

Also, my students are going to test juCi++ in various exercises;) Might be they report an issue or two in a few weeks.

**Comment by zalox** [comment]
I completely removed the python-plugin part in my windows branch. I guess it needs redesigning any way. I think Cygwin is probably the wrong way to go. I have read a lot about it and we need to use MinGW headers to compile, if we want a native windows application. If we use cygwin there aren't any support good support for gtk it seems. MinGW do not support fork(), so we need to figure out a solution for the terminal.

**Comment by eidheim** [comment]
This is abit sad, but great work!

Does MinGW (I take it you mean MinGW-64, as MinGW is pretty old?) support popen? If so, we could create a temporary simple solution for windows, without stdin in the terminal (no idea if Windows even supports stderr). The long term solution would be to use the window libraries to create a separate process I guess then (terminal-win.cc for instance, chosen at CMakeLists.txt).

**Comment by eidheim** [comment]
Btw did you also try 32-bit cygwin? As I understand there are some differences.

**Comment by eidheim** [comment]
(Saw this one was quite long: https://cygwin.com/faq.html#faq.programming.64bitporting)

**Comment by eidheim** [comment]
And by the way, running X application in cygwin is ok, no need for native Windows for now I guess, but up to you.

**Comment by eidheim** [comment]
I finally got Windows up and running on a virtual box. With some fixes to the cmakelists (on both juci and libclangmm), juci now compiles and runs quite nicely on cygwin. Have just found one issue so far: tooltips do not show correctly when the text cursor is moved (I have read that this is a Windows issue, and I will try create a workaround). stdin was already defined in cygwin/windows, and that was the problem.

**Comment by eidheim** [comment]
Ill let you look at the CMakelists. You know this better than me:)

**Comment by zalox** [comment]
Sweet, I was sidetracked by msys2 which uses mingw64 to compile native windows applications. It supports pacman and has a repo with boost, python, gtk etc. However today the repo is down for some reason and I can't download packages. 

If we compile using cygwin, do the user need to have cygwin installed as well?

I quess thats no problem since we are giving the user an environment as well

**Comment by eidheim** [comment]
image
Here you see the result of running "startxwin ./src/juci.exe" from cygwin, and after hitting Project->Compile and Run:)

**Comment by zalox** [comment]
Thats amazing! What is the size of your cygwin?

**Comment by eidheim** [comment]
The way I understand it, is that as long as you have the dll files you can run it even without having cygwin installed. Although if you compile juci with the default gcc-g++ cygwin package you need an X-server to run cygwin. However, if you compile it with the mingw64 cygwin package (under cygwin), you might be able to run juci without an X-server. Sadly the mingw(without 64 that is)-cygwin package has a too old gcc version, so at the moment that one is unusable.

**Comment by eidheim** [comment]
I installed quite some packages, but one sec, Ill check which dll's are needed.

**Comment by eidheim** [comment]
Ok it seems like most of the dll's from c:\cygwin\bin directory is needed, in the juci.exe-path, then some dll's from gtk, boost etc. But we might manage to link all this statically, although not sure if that is the best idea.

**Comment by eidheim** [comment]
Though it might be worth it to test to compile with mingw64 within cygwin, to get a non-X-version (using the cygwin-mingw64 package that is).

**Comment by eidheim** [comment]
Ah yeah, the size of c:\cygwin is around 1.45GB...

**Comment by zalox** [comment]
Thats a mouth full. I will try to do it with cygwin-mingw64 later today or tomorrow. The install shouldn't be greater than ~90 mb.

**Comment by eidheim** [comment]
After a long and painful point and click process, I found that juci uses these libraries under cygwin (compiled for X):
cygatk-1.0-0.dll
cygatk-bridge-2.0-0.dll
cygatkmm-1.6-1.dll
cygatspi-0.dll
cygboost_filesystem-1_57.dll
cygboost_log-1_57.dll
cygboost_system-1_57.dll
cygboost_thread-1_57.dll
cygbz2-1.dll
cygcairo-2.dll
cygcairo-gobject-2.dll
cygcairomm-1.0-1.dll
cygclang.dll
cygclangmm.dll
cygdbus-1-3.dll
cygedit-0.dll
cygEGL-1.dll
cygexpat-1.dll
cygffi-6.dll
cygfontconfig-1.dll
cygfreetype-6.dll
cyggcc_s-1.dll
cyggdk_pixbuf-2.0-0.dll
cyggdk-3-0.dll
cyggdkmm-3.0-1.dll
cyggio-2.0-0.dll
cyggiomm-2.4-1.dll
cygGL-1.dll
cygglapi-0.dll
cygglib-2.0-0.dll
cygglibmm-2.4-1.dll
cyggmodule-2.0-0.dll
cyggobject-2.0-0.dll
cyggraphite2-3.dll
cyggtk-3-0.dll
cyggtkmm-3.0-1.dll
cyggtksourceview-3.0-1.dll
cyggtksourceviewmm-3.0-0.dll
cygharfbuzz-0.dll
cygiconv-2.dll
cygintl-8.dll
cygLLVM-3.5.dll
cygncursesw-10.dll
cygpango-1.0-0.dll
cygpangocairo-1.0-0.dll
cygpangoft2-1.0-0.dll
cygpangomm-1.4-1.dll
cygpcre-1.dll
cygpixman-1-0.dll
cygpng16-16.dll
cygsigc-2.0-0.dll
cygstdc++-6.dll
cygwin1.dll
cygX11-6.dll
cygX11-xcb-1.dll
cygXau-6.dll
cygxcb-1.dll
cygxcb-glx-0.dll
cygxcb-render-0.dll
cygxcb-shm-0.dll
cygXcomposite-1.dll
cygXcursor-1.dll
cygXdamage-1.dll
cygXdmcp-6.dll
cygXext-6.dll
cygXfixes-3.dll
cygXi-6.dll
cygXinerama-1.dll
cygxml2-2.dll
cygXrandr-2.dll
cygXrender-1.dll
cygz.dll

I think one can copy these to a folder also containing juci.exe and start juci from there (from outside cygwin), as long as one have an X-server, everything should work fine (hopefully). My Windows virtual machine decided to do something heavy in the background (thank you Microsoft), so it is unusable atm. Will test later.

**Comment by zalox** [comment]
Disable windows defender and windows update. Those usualy holds my vm.

**Comment by eidheim** [comment]
I think if we compile with the -mwin32 g++ flag (using the default gcc-g++ Cygwin package), we can get juci to run on Windows without the need of an X-server. Not 100% sure, but going to try compile a more simple gtkmm3 application with this flag.

**Comment by eidheim** [comment]
Ok -mwin32 did not do it. One has to compile gtk3 with win32 support instead of X it seems.

**Comment by zalox** [comment]
Thats possible using mingw-w64 i think.

**Comment by eidheim** [comment]
Yeah, hopefully we can manage to compile it there some day. At least we have a working cygwin version. I'll add cmake_command to config.json so that people can use whatever cmake and make program they want (even msys and mingw-w64 ones). Commiting this change soon.

**Comment by eidheim** [comment]
Btw I think even with mingw-w64 under cygwin you still will get X-window gtk unless one compiles gtk with win32. 

However, if one use the compiled win32-gtk libraries from their web-pages, and compile with mingw one should get win32 support (sadly they require mingw it seems). We could perhaps move over to boost::thread instead of std::thread to make this work. I'll leave this up to you.

**Comment by eidheim** [comment]
I'll see if I can fix the tooltip-bug under Windows, after that I guess we can merge the latest changes in libclangmm and jucipp. Give me an hour or so.

**Comment by eidheim** [comment]
Btw, in Linux when I double click on a word like: "some_word_with_underline", only for instance "with" gets selected. Isn't this annoying? Any idea how to fix it? Maybe some option in Linux or GTK somewhere?

**Comment by eidheim** [comment]
I think I figured it out. One has to connect to the gtk3-extend-selection-signal (this one is lacking in gtkmm3). Adding it to my TODO list.

**Comment by eidheim** [comment]
You can merge the pull requests btw (libclangmm and jucipp). They are ok now, even though the Windows version is slow and ugly. Hopefully you figure out how to create a real Windows version:)

**Comment by eidheim** [comment]
Seems like msys2 is the way to go, but it's a bit chaotic with the /mingw* catalogs and several versions of make and cmake (one for msys as well). Can't say I understand it 100%, and the documentation is lacking, especially on how to compile things (maybe you have found a good link?) They do got gtkmm3 for mingw* luckily, but they do not got gtksourceviewmm3... 

Managed to compile libclangmm by linking to clang.dll instead of libclang.a. Not yet managed to compile jucipp.

**Comment by zalox** [comment]
I've been trying to compile gtksourceviewmm with msys2, I had some weird errors. I will tey again tomorrow.

**Comment by eidheim** [comment]
A couple of ideas that might solve your errors: make sure to use the same mingw-toolchain when compiling and the same version of gtksourceviewmm3 as the installed gtksourceview3.

**Comment by eidheim** [comment]
Also, it might be safest to try 32-bit first, since Windows 64-bit might be somewhat different from posix systems, although they might have solved this somehow.

**Comment by eidheim** [comment]
I think you have to install gtksourceview3.12 instead of 3.16, gtksourceviewmm only has versions 3.12 and 3.17. See https://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2/ on how to build packages, one can base it of the current 3.16 sourceview package description at: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-gtksourceview3 (PKGBUILD) and use the makepkg utility. You can create a gtksourceviewmm3 PKGBUILD from this one: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-gtkmm3

**Comment by eidheim** [comment]
Here is btw a PKGBUILD for sourceview3 version 3.12.0 (same as the 3.12 version for gtksourceviewmm): https://github.com/Alexpux/MINGW-packages/tree/4ee82c1def7b9def6720b8586adc6f507fd0102e/mingw-w64-gtksourceview3

**Comment by eidheim** [comment]
I managed to compile juci (without the sys/wait.h's fork/pipe/etc) with gtksourceview3-3.12.0 and gtksourceviewmm3-3.12.0. Will add the PKBUILD files here when I have time. Have to go lecture soon.

**Comment by eidheim** [comment]
Added the packages for gtksourceview3 and gtksourceviewmm3 for MINGW. Compile with:
```sh
makepkg-mingw -sLf
```
and install with `pacman -U`

**Comment by eidheim** [comment]
Fixed the cmake-files. Now you only have to uncomment some Posix code in src/terminal.cc to be able to compile under MSYS2. There are some issues though:)

**Comment by zalox** [comment]
Ok, I will merge this now after I try it of course. Before this merge is to big again :P

**Comment by eidheim** [comment]
I think I can manage to write a src/terminal_win.cc from https://msdn.microsoft.com/en-us/library/windows/desktop/ms682499(v=vs.85).aspx. I'll have a look.

**Comment by eidheim** [comment]
Compilation should now work without modifying terminal.cc (added terminal_win.cc) on Windows. You can merge now (if your tests are successful), it will probably take me a week or so to get the terminal_win.cc to work properly.

**Comment by eidheim** [comment]
At the moment you need to add this to CMAKE_CXX_FLAGS to make juci find std-headers:
-IC:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.2.0/include -IC:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.2.0/../../../../include -IC:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.2.0/include-fixed -IC:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.2.0/../../../../i686-w64-mingw32/include -IC:/msys32/mingw32/lib/gcc/../../include/c++/5.2.0 -IC:/msys32/mingw32/lib/gcc/../../include/c++/5.2.0/i686-w64-mingw32 -IC:/msys32/mingw32/lib/gcc/../../include/c++/5.2.0/backward

**Comment by zalox** [comment]
I think I can fix that by writing finders. I soved it once with clangmm :P

**Comment by eidheim** [comment]
The problem is in libclang, not in a CMakeLists, I was maybe abit unclear! I'll see if there is a permanent solution.

**Comment by eidheim** [comment]
I suspect the problem is here:
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-clang/clang-3.4-add-recent-gcc-versions.patch
The package has not been updated in a while

**Comment by eidheim** [comment]
Run this before running juci on Windows and everything should be fine for now:
```sh
export CXXFLAGS="-IC:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.2.0/include -IC:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.2.0/../../../../include -IC:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.2.0/include-fixed -IC:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.2.0/../../../../i686-w64-mingw32/include -IC:/msys32/mingw32/lib/gcc/../../include/c++/5.2.0 -IC:/msys32/mingw32/lib/gcc/../../include/c++/5.2.0/i686-w64-mingw32 -IC:/msys32/mingw32/lib/gcc/../../include/c++/5.2.0/backward"
```

Hopefully the issue will be fixed soon (http://lists.cs.uiuc.edu/pipermail/cfe-dev/2015-July/043815.html)

**Comment by eidheim** [comment]
I'll hardcode it into source.cc's compiler arguments Tomorrow, and remove it when the clang package for msys2 is fixed.

**Comment by eidheim** [comment]
After this I guess we have a working Windows version:) Only problem I know of so far is that Windows stores files with \r\n instead of \n, and this leads to crazy git diffs. Guess we can just ignore Microsoft here and remove the \r's.

**Comment by zalox** [comment]
Awesome work! The /r/n problem is usually done by detecting how the file is usualy stored. So in my opinion it would be better to default to the os standard, but when it opens a file in for instance unix standard it saves it to the unix standard. In gedit and other editors you can also change save standard inside the editor settings.

**Comment by eidheim** [comment]
You are right, at least it is now up to gtk to store it correctly, however it does not seem that they have implemented using \r\n on Windows when entering new newlines in a Windows file that already contains such characters. But we could add an option much like the auto-tab for this in config.json. There are some things that have higher priority though, so I'll wait with implementing this.

**Comment by eidheim** [comment]
Yikes, notepad also stores æøå in a non-utf8-standard way. Luckily, æøå works when only using MSYS2 applications. We should leave it like this I think, too much work to fix all the non-standard Windows things.

**Pull request merged**
