### PR TITLE
Work on make install

### PR DESCRIPTION
**Pull request by zalox**
Making install as easy
```bash
$ cmake .
$ make 
$ sudo make install
```

### CODE REVIEW

**Comment by zalox** [comment]
I've managed to create the behaviour above. However I am struggling with the library install paths.

**Comment by zalox** [comment]
Some changes to the project:
* removal of config.json, menu.xml and plugins.py. New file files.h which contains these files now
* huge cleanup of Cakelists.txt
* rearrange directory structure

Now it works to say
```bash
$ cmake .
$ make 
$ sudo make install
```
To install juci.

**Comment by zalox** [comment]
@oyvang can you look over and test this. This merge will allow usage of make install, your updated readmes and @eidheim s latest commits. Remember to pull libclangmm master and install it first.

After make install juci can be started from any folder in terminal.

**Comment by zalox** [comment]
@eidheim btw sorry about the latency. I will work on dark theme tomorrow.

**Comment by eidheim** [comment]
No problem! See the GenericView constructor for examples how to read the gtksourceview style colors. I have done some changes to this constructor, will make a pull request Tomorrow most likely, when I'm done with cleanup of the Notebook and Window classes. 

We can use all the gedit styles also, since they use gtksourceview as well, you can find loads of styles out there, maybe you find something that might be close to what you want. 

Sure, can test the install on OS X Tomorrow.

**Pull request merged**
