### PR TITLE
Various fixes and cleanups

### PR DESCRIPTION
**Pull request by eidheim**
* juCi++ should now work quite well on Wayland
* Fixes to debugging when using Ninja
* Spellchecking code moved to `src/source_spellcheck`
* Remote debugging

### CODE REVIEW

**Comment by eidheim** [comment]
The debian stable segmentation fault happens in `lldb::SBDebugger::Initialize();` it seems. I manage to reproduce it when running lldb_test through juCi++ on debian stable. However, running lldb_test or make test in a shell does not produce this segmentation fault. Not sure if we can do anything about this, other than disable lldb_test on debian stable and it's old lldb version.

**Comment by eidheim** [comment]
@zalox tests are not run on appveyor. https://ci.appveyor.com/project/zalox/jucipp-6hwdu/build/1.0.31 should have failed.

**Comment by eidheim** [comment]
@zalox Another test issue: lldb is not installed on the archlinux docker image that travis is using.

**Comment by eidheim** [comment]
Fixing the various platform issues on this PR Tomorrow morning.

**Comment by zalox** [comment]
Is it possible to cross-compile juCi++ in debian with the mingw64-toolchain? If so we should consider adding such build to travis.

**Comment by eidheim** [comment]
No idea, cross-compiling is new to me. Remote debugging is not yet working though, but should soon.

**Comment by eidheim** [comment]
@zalox appveyor is failing. Probably due to updates on MSYS2? The latest commit works on my own upgraded MSYS2.

**Comment by zalox** [comment]
@eidheim I restarted the build. Seems to be working now.

**Comment by zalox** [comment]
Look here **https://github.com/cppit/jucipp/blob/master/appveyor.yml#L8-L11**, we update msys2 before doing anything, so we shouldn't see any problems due to outdated packages.

**Comment by eidheim** [comment]
@zalox this PR is ready for review and merge:)

**Pull request merged**
