### PR TITLE
builds on FreeBSD. related to #253

### PR DESCRIPTION
**Pull request by NuLL3rr0r**
A set of changes that makes juCi++ build without trouble on FreeBSD.

### CODE REVIEW

**Comment by eidheim** [comment]
Thank you. I did some cleanup here: https://github.com/eidheim/jucipp, primarily to make the tests work as well on FreeBSD. Would you mind try this branch? I'll merge after if everything is ok at your end. 

According to https://cmake.org/cmake/help/v3.0/command/link_directories.html:  "Library locations returned by find_package() and find_library() are absolute paths.", so I removed this: https://github.com/cppit/jucipp/pull/254/files#diff-95e351a3805a1dafa85bf20b81d086e6R34 ( `set(global_link_directories ${Boost_LIBRARY_DIRS})`).

**Comment by eidheim** [comment]
You might want to try run the tests as well. Enable with `cmake -DENABLE_TESTING=1 ..` and run `make test` after `make`.

**Comment by NuLL3rr0r** [comment]
Sure, I'll test it and report back shortly.

**Comment by eidheim** [comment]
Also, I forgot earlier, but if you open a source file in jucipp/src/ within juCi++ you should not get any errors. If you do get errors, it is probably because of the hard coded paths here: https://github.com/cppit/jucipp/blob/master/src/source_clang.cc#L211. You might need to add exceptions here as well for FreeBSD.

**Comment by NuLL3rr0r** [comment]
All tests pass just fine:

    [0/1] Running tests...
    Test project /home/babaei/Desktop/jucipp-clean/build
        Start 1: process_test
    1/6 Test #1: process_test .....................   Passed    2.51 sec
        Start 2: cmake_build_test
    2/6 Test #2: cmake_build_test .................   Passed    0.11 sec
        Start 3: source_test
    3/6 Test #3: source_test ......................   Passed    0.23 sec
        Start 4: source_clang_test
    4/6 Test #4: source_clang_test ................   Passed    7.54 sec
        Start 5: lldb_test
    5/6 Test #5: lldb_test ........................   Passed    6.01 sec
        Start 6: git_test
    6/6 Test #6: git_test .........................   Passed    0.13 sec
    
    100% tests passed, 0 tests failed out of 6
    
    Total Test time (real) =  16.58 sec

**Comment by NuLL3rr0r** [comment]
> Also, I forgot earlier, but if you open a source file in jucipp/src/ within juCi++ you should not get any errors. If you do get errors, it is probably because of the hard coded paths here: https://github.com/cppit/jucipp/blob/master/src/source_clang.cc#L211. You might need to add exceptions here as well for FreeBSD.

There was no error.

**Comment by eidheim** [comment]
Glad to hear:) Merging

**Comment by NuLL3rr0r** [comment]
Those hard-coded paths are easy to fix. CMake detects the paths and platforms and pass macros to C++ code.

**Comment by eidheim** [comment]
Ah, feel free to create a pull request on this too, and I'll check if it works on all the platforms we support.

**Comment by NuLL3rr0r** [comment]
Sure, I'll be glad to do that :)

**Comment by eidheim** [comment]
Thank you again:)

**Pull request merged**
