### PR TITLE
Added split window

### PR DESCRIPTION
**Pull request by eidheim**
I think this is stable now, but I guess we should test it a week or so just to be sure. I made some choices to avoid too much complexity, but feel free to give me feedback. 

See also #235.

### CODE REVIEW

**Comment by eidheim** [comment]
@zalox could you look at the cases when travis failed above?

**Comment by milleniumbug** [comment]
This is awesome! There's only a minor issue: width of the split windows isn't remembered across restarts, which I'm fine with, but I'd expect a sane default to be provided, like 50:50 or 60:40, not this:

disproportionate windows

**Comment by eidheim** [comment]
See Notebook::toggle_split, I think the positioning is done correctly. What gtk version do you have? Drag and drop between notebooks is broken in debian testing at the moment for instance, and positioning works perfect on OS X and pretty well on Manjaro. There might be some bug reports on gtk on this I maybe that might shed some light on the issues.

**Comment by eidheim** [comment]
@milleniumbug Found this regarding the positioning: https://bugzilla.gnome.org/show_bug.cgi?id=765676. Would you mind test if the workaround works?

**Comment by milleniumbug** [comment]
Replacing `set_position(get_width()/2);` with `int width = get_width(); set_position(width/2-1); set_position(width/2);` did nothing.

Tried debugging it, and the value of `width` at this point is 479. Now I suspect this is `i3-wm` specific issue (the window manager I'm using)

**Comment by zalox** [comment]
@eidheim You should pull in master into this branch, so we get CI with windows as well :)

**Comment by zalox** [comment]
@eidheim Regarding the failed builds, it seems travis fails due to a docker/ubuntu bug, and windows seems to fail due to resource management in appveyor. I think you can restart builds if any of these scenarios happen, if not I shall give you the missing permissions.

**Comment by eidheim** [comment]
@milleniumbug split window position should be fixed in https://github.com/cppit/jucipp/pull/239/commits/0e0ef9ba19321853aa2b7119726a16d93debb27d (last commit above). At least it's correct now in Manjaro.

**Comment by eidheim** [comment]
@zalox this PR is getting ready for merge. Maybe a day or two more with testing, and after @milleniumbug has verified that the split window position is correct now.

**Comment by milleniumbug** [comment]
Can confirm that now after restart waits for a moment and then sets the divider 50:50.

**Comment by eidheim** [comment]
@zalox this PR seems quite stable. Feel free to merge after review.

**Comment by eidheim** [comment]
Merged, since new important PR is coming.

**Pull request merged**
