### PR TITLE
Many bug fixes and improved clang indentation

### PR DESCRIPTION
**Pull request by eidheim**
Tested on Ubuntu 14, debian stable/testing, OS X and MSYS2. 

The clang indentation should now work flawlessly (hopefully) in every case, even in multi-line expressions. 

Would be nice if we could merge this soon, after you have tested it of course. If there are issues, I will try fix it Today or Tomorrow, but I will not commit more features before it's merged:)

### CODE REVIEW

**Comment by zalox** [comment]
Can you try to open api.cc and wait until parsing is done? It crashes on debian testing sometimes.

**Comment by zalox** [comment]
I'm using libboost1.55-all-dev btw, since debian testing has 1.58 as well.

**Comment by eidheim** [comment]
libclang: crash detected during reparsing

Creating an issue on this, it also crashed on OS X

**Comment by eidheim** [comment]
We'll fix this at a later point I guess.

**Comment by eidheim** [comment]
Is the indentation acceptable do you think? Later I'll add "set indentation char and size" and "auto indent file" to the menu.

**Comment by zalox** [comment]
This is the first time indenting has worked on my laptop for some reason. So I like it.

**Comment by eidheim** [comment]
I know there was a problem with key states in Ubuntu, but that is fixed now.

**Comment by eidheim** [comment]
Btw, we should maybe read the menu-xml directly from files.h instead of .juci/... Maybe that will fix the Windows menu issue as well?

**Pull request merged**
