### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by eidheim**
Tested on most platforms, ready for merge.

### CODE REVIEW

**Comment by eidheim** [comment]
The last commit needs some more testing before we merge.

**Comment by eidheim** [comment]
Tested on most platforms, again ready for merge.

**Comment by eidheim** [comment]
@zalox: have you looked through all of this PR?

**Comment by eidheim** [comment]
I'm merging this PR now since it contains important bug fixes.

**Comment by zalox** [comment]
I reviewed this, I just forgot to merge. I guess exams are messing with my brain.

**Pull request merged**
