### PR TITLE
A quick pull request of two neat commits till Monday

### PR DESCRIPTION
**Pull request by eidheim**
If ok, could we merge these two commits before Monday morning?

### CODE REVIEW

**Comment by eidheim** [comment]
Tested and works on Debian stable, OS X and Windows.

**Comment by zalox** [comment]
I will also introduce the "about popup" before tomorrow morning.

**Comment by eidheim** [comment]
Splendid!

**Comment by eidheim** [comment]
The other commits seem to be working as well on all the OS'es I have.

**Comment by zalox** [comment]
If I get time I will try to make a bot to compile the master each time it updates. At least on debian and ubuntu.

**Comment by zalox** [comment]
I just merged this. I introduced version number 0.9.1 for some reason.

**Pull request merged**
