### PR TITLE
Cleanup of refactoring methods

### PR DESCRIPTION
**Pull request by eidheim**
@zalox you should probably test this a bit too. I think it's 100% and have tested on most platforms.

### CODE REVIEW

**Comment by eidheim** [comment]
@zalox Ready for merge after you have tested the changes. Especially the wait dialogs are a significant improvement.

**Comment by eidheim** [comment]
Merging now since refactor rename, goto implementation and goto usage is greatly improved compared to current master, and since @zalox is busy with exams:)

**Comment by zalox** [comment]
Thanks! I got a working CI with clang/g++/scanbuild now. It runs 15 different scenarios in about 20 minutes. I think its a good move to merge that branch soon to get more builds and catch reoccuring problems, doing so wont affect the users. I need to merge a feature branch first though.

**Comment by eidheim** [comment]
Nice! Feel free to merge the CI PR when you think it's ready:) You know this better than me.

**Pull request merged**
