### PR TITLE
form some unix external commands in a broader context(not linux-centric)

### PR DESCRIPTION
**Pull request by uncleyear**
+ using more version suffixes(at least on FreeBSD they are "50", "40", etc; for example - "clang-format50");
+ using more pathes to search for commands(for example - FreeBSD uses "/usr/local/bin" for binaries(or scripts invoking real commands) of llvm and other packages);

### CODE REVIEW

**Comment by eidheim** [comment]
@uncleyear Thank you! I made the approach more general in https://github.com/eidheim/jucipp/commit/0b58eef67866ad17a792081f137a3071a6aa9f1c. Please let me know if this works on your system.

**Comment by uncleyear** [comment]
Hi Ole! Yes, this works. 04.11.2017, 11:18, "Ole Christian Eidheim" <notifications@github.com>:@uncleyear Thank you! I made the approach more general in eidheim/jucipp@0b58eef. Please let me know if this works on your system.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.   С наилучшими пожеланиями.

**Comment by eidheim** [comment]
Thank you again. I did some further cleanup and improved checks in https://github.com/cppit/jucipp/commit/e931840e83ca8501a18a209aef5f4f7d78c7ce8e that I just pushed to master. Hopefully everything still works in your case.

**Comment by uncleyear** [comment]
Hi Ole! That works also.05.11.2017, 22:37, "Ole Christian Eidheim" <notifications@github.com>:Thank you again. I did some further cleanup and improved checks in e931840 that I just pushed to master. Hopefully everything still works in your case.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




С наилучшими пожеланиями.

**Pull request closed without merging**
