### PR TITLE
Major cleanup

### PR DESCRIPTION
**Pull request by eidheim**
Added cmake.h and cmake.cc to handle parsing of CMakeLists.txt files. Also fixed compile, and compile and run. Quite a few files changed, thus the pull request. 

Should find the cmake-root as well as project name in most conditions, and the executables (although, only the first one is selected in window.cc at this point). Be aware that running juci twice in Debian Stable using Gnome does not work for some reason, though other applications can be run through Juci without problem in Debian Stable.)

Remember to delete ~/.juci/config/config.json before testing. 

Going to add a way to stop the running application in the terminal at some point.

### CODE REVIEW

**Comment by zalox** [comment]
Cool, I'm soon done with theming. It looks like we can merge without problems as I can't see many changes in the files I've been.

Syntax highlighting, gui-elements and menu all has different config files, so that's kind of messy.

**Comment by eidheim** [comment]
Great, like I said in another post, it's not THAT messy with the various config-files. The new Atom editor also has at least 3 config files (1 for theme, 1 for syntax highlighting, and 1 for other stuff)

**Comment by zalox** [comment]
What are your thoughts about the namespacing etc in juci now?

**Comment by eidheim** [comment]
It's ok I guess, no need to add Juci:: in front of everything since this is not a library I'm thinking, but not sure.

**Comment by eidheim** [comment]
By the way, with the new popen2 it is possible to stream input into the compile&run application through the terminal window. I'll fix this at some point.

**Comment by eidheim** [comment]
Forgot, I added bold to stderr messages in terminal.

**Comment by zalox** [comment]
I have finished the theming semantics, just need to find or create a nice looking theme. I will merge this and the themes later today if I manage :rocket:

**Comment by eidheim** [comment]
Splendid!

I'm trying to fix a crash in the fork/pipe/dup/waitpid/kill-madness when running several programs from Juci. Amazing it is so difficult to start a separate process, get the streams and kill it...

**Comment by zalox** [comment]
Btw, when I edit the CMakeList.txt the cmake command runs smoothly. However if I open for instance jucipp/src/CMakeLists.txt and it fails due to not being the top level CMakeLists.txt

**Comment by eidheim** [comment]
There has to be a open directory with the path included in the CMakeLists.txt path for it to rerun cmake at the moment. Might be an idea to change that sure. Adding a TODO there (Notebook::save()).

**Comment by eidheim** [comment]
Was hoping we could call more complex commands in Juci from a menuitem opening a command entry (like in emacs), like "make && ./src/juci", but at the moment only "./src/juci" would work. Guess its ok for now.

**Comment by eidheim** [comment]
We can now run complex commands in terminal (like "make && ./src/juci")! Its soon a fully working terminal window:)

**Comment by zalox** [comment]
@eidheim I'm currently working on windows support. I have managed to compile everything except Terminal. I get "invalid conversion from __FILE to int"

**Comment by eidheim** [comment]
Nice! I'll look at that error Today or Tomorrow. Where in terminal.cc was the error reported?

**Comment by zalox** [comment]
https://gist.github.com/zalox/aa8ab4730716a4e483aa

**Comment by eidheim** [comment]
Are you compiling under Cygwin btw?

**Comment by zalox** [comment]
Yes, I just installed boost, gtksourceviewmm, g++, cmake, make and git through cyg-get and compiled. I had to change some casts to compile the other classes, other than that no hiccups.

**Comment by zalox** [comment]
The theming branch is updated with both your changes and mine  btw.

**Comment by eidheim** [comment]
Can we merge it to the master do you think? Before the pull is getting too big? I saw one small piece missing from juci.cc (https://github.com/eidheim/jucipp/commit/ee7da8476bcfaec4552c21efa02bfd4f49c74b65), might be hard to find these later on maybe. Or is the theming not ready for the master branch just yet?

**Comment by zalox** [comment]
I actually noticed it myself, I will push now.

**Pull request merged**
